apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhost-py
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myhost-py
  template:
    metadata:
      labels:
        app: myhost-py
    spec:
      containers:
      - name: myhost-py
        image: densukest/myhost-py:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
