apiVersion: v1
kind: Pod
spec:
  containers:
  - name: db
    image: mariadb:10
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 3306
    env:
      # MySQL_DATABASE/USER/PASSWORDをそれぞれ書き換え、dbconfig.yml上のconfigmap/secretから取得するようにしましょう
      - name: MYSQL_DATABASE
        value: wordpress
      - name: MYSQL_USER
        value: wordpress
      - name: MYSQL_PASSWORD
        value: wpadmin
      - name: MYSQL_RANDOM_ROOT_PASSWORD
        value: "1"
