kind: ConfigMap
apiVersion: v1
metadata:
  name: dbconfig
  namespace: default
data:
  wpdb: wordpress
  wpuser: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: dbconfig
  namespace: default
type: Opaque
data:
  wppass: "d3BhZG1pbg=="
