apiVersion: v1
kind: Pod
metadata:
  name: exam03
  labels:
    name: exam03
spec:
  containers:
  - name: exam03
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    command:
      - "sh"
    args: ["-c", "free | grep ^Swap"]
  restartPolicy: Never
