apiVersion: v1
kind: Pod
metadata:
  name: exam02
  labels:
    name: exam02
spec:
  containers:
  - name: exam02
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    command:
      - "ip"
    args: ["a"]
  restartPolicy: Never
