apiVersion: v1
kind: Pod
metadata:
  name: exam04
  labels:
    name: exam04
spec:
  containers:
  - name: exam04
    image: densukest/exam04-20201106
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    command:
      - "bash"
    args: ["--version"]
  restartPolicy: Never
